Merge from 1.1 branch rev 410654 - Fix typo which can cause NoClassDefFoundErrors in client environments
git-svn-id: https://svn.apache.org/repos/asf/geronimo/trunk@410745 13f79535-47bb-0310-9956-ffa450edef68