Changed XML Beans Maven plugin to prior version as the newly released SNAPSHOT (20061223) causes a NoClassDefFoundError when building ServiceBuilder
git-svn-id: https://svn.apache.org/repos/asf/geronimo/server/trunk@490544 13f79535-47bb-0310-9956-ffa450edef68