Fix typo which can cause NoClassDefFoundErrors in client environments
git-svn-id: https://svn.apache.org/repos/asf/geronimo/branches/1.1@410654 13f79535-47bb-0310-9956-ffa450edef68