Cleanup some bad spec dependencies. The dependency in client-system was causing a NoClassDefFoundError in some circumstances
git-svn-id: https://svn.apache.org/repos/asf/geronimo/server/trunk@546699 13f79535-47bb-0310-9956-ffa450edef68